import = ["~/Repos/dotfiles/alacritty/catppuccin-macchiato.toml"]

[font]
size = 14

[shell]
program = "/usr/bin/fish"

# [font.normal]
# family = "UbuntuMono Nerd Font"

# [window]
# decorations = "none"

# [window.padding]
# x = 7
# y = 0
