[env]
term = "xterm-256color"

[font]
size = 22 

[terminal.shell]
program = "/opt/homebrew/bin/zsh"
args = [ "--login" ]

[font.normal]
family = "UbuntuMono Nerd Font"

[window]
option_as_alt = "Both"

[general]
import = ["~/.config/alacritty/themes/catppuccin-macchiato.toml"]

[terminal]
