import = ["~/.dotfiles/alacritty/catppuccin-macchiato.toml"]

[env]
term = "xterm-256color"

[font]
size = 22 

[shell]
program = "/usr/local/bin/zsh"
args = [ "--login" ]

[font.normal]
family = "UbuntuMono Nerd Font"

[window]
option_as_alt = "Both"
